### ISSUE TITLE
API Reference page fails to load

### ISSUE THREAD

**Issue by Sembiance** [drashland/drash#580] opened 2021-11-17 17:40 UTC
## Summary

The API Reference URL linked to in the docs fails to load.

## Steps To Reproduce The Bug

1. Visit API Reference page: https://doc.deno.land/https/deno.land/x/drash/mod.ts
2. See error message: `An unexpected error has occurred.`

**Comment by ebebbington** [comment] 2021-11-17 17:42
Duplicate of #547, thanks @Sembiance but this issue is dependant on Deno, nothing we can do at the moment :/

**Closed by ebebbington** 2021-11-17 17:42 UTC

**Comment by ebebbington** [comment] 2021-11-18 01:29
@Sembiance if you needed the documentation for a specific class or method, feel free to let me know and i can supply it manually

**Comment by Sembiance** [comment] 2021-11-18 02:06
> @Sembiance if you needed the documentation for a specific class or method, feel free to let me know and i can supply it manually

Thanks, but I'm all set.
